"""relationship and foreign keys [like/post/saved/comment/user]


Revision ID: d42821bd1c8e
Revises: 
Create Date: 2023-10-30 23:24:55.553883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42821bd1c8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_comments_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name=op.f('uq_comments_id'))
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_likes_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_likes_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('likes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_posts_comment_id_comments')),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_posts_contractor_id_contractors')),
    sa.ForeignKeyConstraint(['likes_id'], ['likes.id'], name=op.f('fk_posts_likes_id_likes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posts_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name=op.f('uq_posts_id'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('e_mail', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name=op.f('uq_users_id'))
    )
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('secondary_address', sa.String(), nullable=True),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_contractors_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name=op.f('uq_contractors_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_contractors_user_id'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('transmitter_id', sa.Integer(), nullable=True),
    sa.Column('receptor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receptor_id'], ['users.id'], name=op.f('fk_reviews_receptor_id_users')),
    sa.ForeignKeyConstraint(['transmitter_id'], ['users.id'], name=op.f('fk_reviews_transmitter_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name=op.f('uq_reviews_id'))
    )
    op.create_table('saved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_saved_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name=op.f('uq_saved_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved')
    op.drop_table('reviews')
    op.drop_table('contractors')
    op.drop_table('users')
    op.drop_table('posts')
    op.drop_table('likes')
    op.drop_table('comments')
    # ### end Alembic commands ###
