"""fixes relationships

Revision ID: ecfccc32dfc9
Revises: d42821bd1c8e
Create Date: 2023-11-08 21:18:49.226065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfccc32dfc9'
down_revision = 'd42821bd1c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_comment_id_comments', type_='foreignkey')
        batch_op.drop_constraint('fk_posts_likes_id_likes', type_='foreignkey')
        batch_op.drop_column('likes_id')
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('likes_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_posts_likes_id_likes', 'likes', ['likes_id'], ['id'])
        batch_op.create_foreign_key('fk_posts_comment_id_comments', 'comments', ['comment_id'], ['id'])

    # ### end Alembic commands ###
